### ISSUE TITLE
Modules should tolerate non-xclim variable names

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1129]
### Setup Information

- Xclim version: master
- Python version: all
- Operating System: all

### Description

When creating an indicator through a Yaml file and using the `input: {old: new}` construct to rename an input, xclim currently need a name (`new`) that exists in `variables.yml`. It fails otherwise. This was done because this construct activates the CF checks, so standard CF attributes must be available and the only way currently is through that internal file (or adding them dynamically to `xclim.core.utils.VARIABLES`).

### Steps To Reproduce

```yaml
realm: land
indicators:
  freq_analysis:
    base: freq_analysis
    input: {da: Dis}
    parameters:
      mode: max
      t: [2, 20, 100, 350]
      dist: genextreme
```
When loading this as an xclim module, it will fail with :
```
ValueError: Compute argument da was mapped to variable Dis which is not understood by xclim or CMIP6. Please use names listed in `xclim.core.utils.VARIABLES`.
```

### Additional context

I think we could simply downgrade the error to a warning and mention that the unknown name means no CF-checks will be performed.

A fancier solution would be to provide tools to add variables to the known list. If it could be made through the yaml file and be module-dependent, that seems to me to be elegant enough?

@RondeauG 

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
