### ISSUE TITLE
Cannot set virtual indicator realm individually

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#1425]
### Setup Information

- Xclim version: dev
- Python version: 3.10

### Description

The realm of individual indicators in yaml files is ignored. It is systematically overwritten by the global realm attribute, and it it doesn't exist, the default `atmos`. 

### Steps To Reproduce
Load the following yaml file with `xc.core.indicator.build_indicator_module_from_yaml` and inspect each indicator's realm. It will be set to `seaIce`. 
```
doc: |

realm: seaIce

indicators:
  jetstream:
    base: jetstream_metric_woollings
    src_freq: M
    realm: atmos
    keywords: spatial_reduction
  sea_ice_extent:
    base: sea_ice_extent
    realm: ocean
    src_freq: M
    keywords: spatial_reduction
```

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
