### ISSUE TITLE
Add White Christmas and Perfect Christmas indicators

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#2029]
### Addressing a Problem?

This is more of an added extra based on a page I found on Environment Canada: https://www.canada.ca/en/environment-climate-change/services/weather-general-tools-resources/historical-christmas-snowfall-data.html

Two indicators are listed here:
- "White Christmas": "Snow on the ground of 2 cm or more on Christmas morning at 7 a.m. EST"
- "Perfect Christmas": "Snow on the ground of 2 cm or more on Christmas morning and snow in the air sometime Christmas day"

This could be a festive addition to the indicators list ❄

### Potential Solution

Adding these indicators using the following variables:

- `snd > "2 cm"` where `date == "12-25"`
- (`snd > "2 cm"` && `prsn > "1 cm"`) where `date == "12-25"`

### Additional context

Adding these indicators for data with standard calendars is probably inconsequential, but some care might be needed when dealing with some non-standard calendars (`360-day`, specifically).

This would really only be useful for examining historical weather records, similar to what Environment Canada is presenting.

In order for this to be of value to projected climate data, broadening the windows of number of days around Dec 25th could be useful (±2 days?) if we want to establish statistical probability of the conditions.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coxipi** [comment]
"Perfect" Christmas is quite subjective ... hehe

We had this indicator in PINS:

```yaml
  christmas_snw_days:
    base: snw_season_length
    cf_attrs:
      long_name: Christmas days with snow
      description: Number of days with a snow cover in a 16 days window around Christmas time.
    parameters:
      thresh: 4 kg m-2
      freq: AS-JUL
      indexer:
        date_bounds:
          - 12-19
          - 01-03
```
