### ISSUE TITLE
Get the autodoc to work on readthedocs

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#21]
### Description

Make sure the API docs build on readthedocs.
May need to set a conda environment for readthedocs. 

See bird-house for an example of how this is done. 

readthedocs.yml
```
build:
    image: latest
 python:
    version: 3.6
 conda:
    file: environment.yml
```
