### ISSUE TITLE
Add dtr in variables

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xclim#2146]
### Generic Issue

Would it be ok to add `dtr` to data/variables.yml ?

Un des health checks de mon workflow est ` cfcheck_from_name` qui regarde les définitions dans le yml.
J'ajouterais:
```
  dtr:
    canonical_units: K
    cell_methods: "time range within days"
    description: Diurnal temperature range.
    dimensions: "[temperature]"
    standard_name: air_temperature
```

Si c'est cassant pour xclim ou vous trouvez que ça a pas rapport, je peux juste aussi l'enlever de mon workflow. but I thought I would check if this is possible first.

EDIT: peut-être que les units devraient être delta_K ?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
