### ISSUE TITLE
A stronger YAML system for virtual indicators

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#828]
Now that the virtual submodule system has been tested in a few in-house cases, and before it is used extensively, I think we need to rethink some of it.

Issues:

1. No validation. Extra keys do not trigger errors. We have real use case where one entry was misplaced and resulted in wrong indicators.
2. Very relax specification. In order to accept clix-meta yaml as-is AND to have a specification that was closer to xclim's internals, the code in `Indicator.from_dict` is quite complex.

Ideas:

1. Explore [yamale](https://github.com/23andMe/Yamale) or [schema](https://github.com/keleshev/schema) for YAML validation. The first as the interesting feature that the whole spec would sit in a yaml file. xclim wouldn't need to depend on a extra package, but would provide the tools needed so users can perform the validation, if they so wish. The second has more users.

2. Rethink the whole yaml spec and make it strict. Make it so it mirrors the structure of indicator objects better. Then, add a function that translates clix-meta yaml to this xclim yaml. We don't need this runtime-compatibility with clix-meta, we only need some way of updating xclim when clix-meta  is updated.

**Comment by huard** [comment]
Questions: 
- Would a strict schema have catched the error?
- How strict is the clix-meta schema? Would a stricter schema help? 
- Why do we need to edit the clix-meta yaml ?

**Comment by aulemahal** [comment]
> Would a strict schema have catched the error?

Depends on what we do. The problem was a misplaced key and currently "extra" keys in a yaml are not detected/dealt with. One could store more info than xclim needs in their yaml. This was done because of all the extra keys of clix-meta we don't use, but I do think it makes sense in general. Also, checking for this would _add_ complexity, no remove it. So my vision is no.

> How strict is the clix-meta schema? Would a stricter schema help?

It's stricter than ours in the sense that it is straightforward. There is only one way to write things. But because it doesn't fit xclim's vocabulary, xclim's yaml schema includes more than one way of specifying things. I believe a stricter schema would be easier to understand, reduce code complexity and, by a happy side effect, reduce risk of errors.

> Why do we need to edit the clix-meta yaml ?

For the reason told above. What I am suggesting is more like : pull out clix-meta-specific parsing to another function. This way, `Indicator.from_dict` could be nicer to read and maintain. Adding the `cf` submodule to xclim would need to pass the clix-meta yaml through this second function, either at import time or only when clix-meta gets updated.

## Examples.

What it is now:
```yaml
# Taken from cf.yml which is directly taken from clix-meta
  txx:
    reference: ETCCDI
    period:  
      allowed:  # This is broken in clix-meta, why a mapping? A list would suffice.
        annual:
        seasonal:
        monthly:
      default: annual
    output:
      var_name: "txx"
      standard_name: air_temperature
      long_name: "Maximum daily maximum temperature"
      units: "degree_Celsius"
      cell_methods:
        - time: maximum within days
        - time: maximum over days
    input:
      data: tasmax
    index_function:  # xclim calls this "compute" in the Indicator class
      name: statistics
      parameters:
        reducer:
          kind: reducer
          reducer: max
      # To simplify, xclim also accepts this, the "kind" key means nothing since the parameter is passed as a string.
        reducer: max
    ET:  # This section means nothing in xclim
      short_name: "txx"
      long_name: "Maximum daily maximum temperature"
      definition: "Maximum value of daily TX"
      comment: "maximum of daily maximum temperature"
```

The same entry, but after improvements to the yaml schema, as suggested here.
```yaml
  txx:
    references: ETCCDI
    allowed_periods: [A, Q, M]
    var_name: "txx"
    standard_name: air_temperature
    long_name: "Maximum daily maximum temperature"
    units: "degree_Celsius"
    cell_methods: "time: maximum over days"
    input:
      data: tasmax
    compute: generic.statistics
    parameters:
      reducer: max
      freq:
        default: YS
```

Here I removed the "output"  section, so this mirros the way indicators are declared programmatically in `xclim/indicators/*`.  This way, only the `input` and `parameters` need to be parsed with a special attention in `Indicator.from_dict`, the rest is (almost) directly passed as `**kwargs` to the `__init__`.
